.PHONY: clean All

All:
	@echo "----------Building project:[ CarpetCleaning - Debug ]----------"
	@cd "CarpetCleaning" && "$(MAKE)" -f  "CarpetCleaning.mk"
clean:
	@echo "----------Cleaning project:[ CarpetCleaning - Debug ]----------"
	@cd "CarpetCleaning" && "$(MAKE)" -f  "CarpetCleaning.mk" clean
