.PHONY: clean All

All:
	@echo "----------Building project:[ Drill - Debug ]----------"
	@cd "Drill" && "$(MAKE)" -f  "Drill.mk"
clean:
	@echo "----------Cleaning project:[ Drill - Debug ]----------"
	@cd "Drill" && "$(MAKE)" -f  "Drill.mk" clean
