.PHONY: clean All

All:
	@echo "----------Building project:[ NameAndAge - Debug ]----------"
	@cd "NameAndAge" && "$(MAKE)" -f  "NameAndAge.mk"
clean:
	@echo "----------Cleaning project:[ NameAndAge - Debug ]----------"
	@cd "NameAndAge" && "$(MAKE)" -f  "NameAndAge.mk" clean
